import { MapSpot } from '@/types';

export const INITIAL_MAP_SPOTS: MapSpot[] = [
  // --- ТУАЛЕТЫ (TOILETS) ---
  {
    id: 'toilet-kaznu-guk',
    title: 'Общественный туалет у ГУК КазНУ',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2245,
    lng: 76.9218,
    address: 'Кампус КазНУ им. аль-Фараби, возле ГУК',
    isFree: true,
    priceInfo: 'Бесплатно для студентов',
    hours: '08:00 – 21:00',
    description: 'Чистый студенческий санузел с горячей водой, мылом и сушилками для рук. Доступен по студенческому билету или свободно.',
    tags: ['Кампус', 'КазНУ', 'Бесплатно', 'Чистый'],
  },
  {
    id: 'toilet-satbayev-polytech',
    title: 'Туалет в главном корпусе Satbayev University',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2375,
    lng: 76.9268,
    address: 'ул. Сатпаева, 22 (Главный учебный корпус)',
    isFree: true,
    priceInfo: 'Бесплатно',
    hours: '07:30 – 20:00',
    description: 'Санузел на 1 и 2 этажах ГУК Политеха. Оснащен сенсорными дозаторами и кабинками для маломобильных граждан.',
    tags: ['Satbayev', 'Политех', 'Бесплатно', 'Доступно'],
  },
  {
    id: 'toilet-promenade-mall',
    title: 'Туалет в ТЦ Promenade',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2392,
    lng: 76.9235,
    address: 'пр. Абая, 44а (уг. Байтурсынова), 2 этаж',
    isFree: true,
    priceInfo: 'Бесплатно для посетителей',
    hours: '10:00 – 22:00',
    description: 'Просторные бесплатные уборные в зоне фудкорта. Всегда есть туалетная бумага и зеркала.',
    tags: ['ТРЦ', 'Байтурсынова', 'Бесплатно'],
  },
  {
    id: 'toilet-panfilov-street',
    title: 'Модульный туалет на ул. Панфилова',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2530,
    lng: 76.9458,
    address: 'ул. Панфилова, уг. ул. Кабанбай батыра',
    isFree: false,
    priceInfo: '50 ₸ (Оплата Kaspi QR / Картой)',
    hours: 'Круглосуточно 24/7',
    description: 'Современный автоматический теплый городской модуль. Вход по бесконтактной оплате или Kaspi QR.',
    tags: ['Городской', 'Панфилова', '24/7', 'Kaspi QR'],
  },
  {
    id: 'toilet-metro-almaly',
    title: 'Санузел на станции метро «Алмалы»',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2520,
    lng: 76.9442,
    address: 'Станция метро Алмалы (под ул. Панфилова)',
    isFree: true,
    priceInfo: 'Бесплатно для пассажиров',
    hours: '06:20 – 00:00',
    description: 'Официальный санузел алматинского метрополитена. Обратитесь к дежурному у турникетов.',
    tags: ['Метро', 'Алмалы', 'Бесплатно'],
  },
  {
    id: 'toilet-metro-baykonur',
    title: 'Санузел на станции метро «Байконур»',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2395,
    lng: 76.9210,
    address: 'пр. Абая / ул. Байтурсынова (метро Байконур)',
    isFree: true,
    priceInfo: 'Бесплатно для пассажиров',
    hours: '06:20 – 00:00',
    description: 'Расположен на платформе станции метро, очень удобно для студентов Политеха и МУИТ.',
    tags: ['Метро', 'Байконур', 'Бесплатно'],
  },
  {
    id: 'toilet-dostyk-plaza',
    title: 'Санузлы ТРЦ Dostyk Plaza',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2335,
    lng: 76.9568,
    address: 'мкр. Самал-2, 111 (пр. Достык / Жолдасбекова)',
    isFree: true,
    priceInfo: 'Бесплатно',
    hours: '10:00 – 23:00',
    description: 'Образцовые санузлы на 1, 2 и 3 этажах (возле фудкорта и кинотеатра). Регулярная уборка каждые 20 минут.',
    tags: ['ТРЦ', 'Dostyk Plaza', 'Бесплатно', 'Комфорт'],
  },
  {
    id: 'toilet-panfilov-park',
    title: 'Городской туалет в Парке 28 Панфиловцев',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2592,
    lng: 76.9535,
    address: 'Парк им. 28 гвардейцев-панфиловцев (южная аллея)',
    isFree: false,
    priceInfo: '50 ₸',
    hours: '09:00 – 21:00',
    description: 'Стационарный парк-туалет рядом с Вознесенским собором. Есть раковины и детская зона.',
    tags: ['Парк', 'Центр'],
  },
  {
    id: 'toilet-mega-center',
    title: 'Санузлы ТРЦ MEGA Alma-Ata',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2030,
    lng: 76.8925,
    address: 'ул. Розыбакиева, 247',
    isFree: true,
    priceInfo: 'Бесплатно',
    hours: '10:00 – 22:00',
    description: 'Бесплатные комфортные туалеты во всех галереях ТРЦ МЕГА.',
    tags: ['ТРЦ', 'МЕГА', 'Бесплатно'],
  },
  {
    id: 'toilet-arbat-passage',
    title: 'Туалет в ТЦ «Пассаж» на Арбате',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2625,
    lng: 76.9420,
    address: 'ул. Жибек Жолы, 50 (пешеходный Арбат)',
    isFree: true,
    priceInfo: 'Бесплатно',
    hours: '10:00 – 21:00',
    description: 'Туалет на 3 этаже торгового центра. Удобная локация при прогулке по Арбату.',
    tags: ['Арбат', 'Бесплатно', 'Центр'],
  },

  // --- БЕСПЛАТНЫЙ WI-FI (FREE WI-FI) ---
  {
    id: 'wifi-kaznu-library',
    title: 'Студенческая сеть KazNU-Open-WiFi',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2252,
    lng: 76.9230,
    address: 'Библиотека Аль-Фараби, КазНУ',
    isFree: true,
    wifiSpeed: '120 Мбит/с',
    hours: '08:00 – 22:00',
    description: 'Открытая высокоскоростная сеть для студентов. Отлично подходит для скачивания учебников и видео-лекций.',
    tags: ['Wi-Fi', 'КазНУ', '120 Mbps', 'Без пароля'],
  },
  {
    id: 'wifi-satpaev-square',
    title: 'Городской Wi-Fi в сквере Сатпаева',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2380,
    lng: 76.9275,
    address: 'Сквер им. Сатпаева (напротив Политеха)',
    isFree: true,
    wifiSpeed: '65 Мбит/с',
    hours: 'Круглосуточно',
    description: 'Общественная точка доступа Almaty-City-WiFi с устойчивым сигналом на скамейках в парке.',
    tags: ['Wi-Fi', 'Сквер', 'Открытая сеть'],
  },
  {
    id: 'wifi-panfilov-pedestrian',
    title: 'Открытый Wi-Fi на ул. Панфилова',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2540,
    lng: 76.9455,
    address: 'Пешеходная зона Панфилова (между Толе би и Кабанбай)',
    isFree: true,
    wifiSpeed: '85 Мбит/с',
    hours: 'Круглосуточно',
    description: 'Городской проект OpenAlmaty_WiFi. Подключение в один клик через SMS-авторизацию.',
    tags: ['Wi-Fi', 'Панфилова', 'Улица'],
  },
  {
    id: 'wifi-arbat-free',
    title: 'Almaty Free WiFi на Арбате',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2620,
    lng: 76.9430,
    address: 'ул. Жибек Жолы (Арбат)',
    isFree: true,
    wifiSpeed: '70 Мбит/с',
    hours: 'Круглосуточно',
    description: 'Покрывает всю прогулочную зону Арбата от Абылай хана до Кунаева.',
    tags: ['Wi-Fi', 'Арбат', 'Бесплатно'],
  },
  {
    id: 'wifi-dostyk-plaza',
    title: 'Высокоскоростной Wi-Fi в Dostyk Plaza',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2338,
    lng: 76.9572,
    address: 'Самал-2, 111, ТРЦ Достык Плаза',
    isFree: true,
    wifiSpeed: '150 Мбит/с',
    hours: '10:00 – 23:00',
    description: 'Сеть DostykPlaza_Free без ограничений по времени. Стабильно ловит в зоне коворкинг-кафе и фудкорта.',
    tags: ['Wi-Fi', 'Dostyk Plaza', '150 Mbps'],
  },

  // --- РОЗЕТКИ И МЕСТА ДЛЯ УЧЕБЫ (OUTLETS / STUDY) ---
  {
    id: 'outlet-smartspace',
    title: 'SmartSpace Coworking (розетки + столы)',
    category: 'outlet',
    categoryLabel: 'Розетки / Учеба',
    lat: 43.2398,
    lng: 76.9185,
    address: 'пр. Абая, 52/2 (ст. метро Байконур)',
    isFree: false,
    priceInfo: 'Дневной студенческий билет со скидкой StudCity',
    outletCount: 'Розетка у каждого места (50+)',
    hours: '09:00 – 23:00',
    description: 'Идеальное тихое место для учебы с высокоскоростным интернетом и удлинителями для ноутбуков.',
    tags: ['Розетки', 'Коворкинг', 'Сессия'],
  },
  {
    id: 'outlet-kaznu-hub',
    title: 'Студенческий коворкинг ГУК КазНУ',
    category: 'outlet',
    categoryLabel: 'Розетки / Учеба',
    lat: 43.2255,
    lng: 76.9225,
    address: 'Кампус КазНУ, корпус ГУК, цокольный этаж',
    isFree: true,
    priceInfo: 'Бесплатно для студентов',
    outletCount: '30+ розеток и Type-C зарядки',
    hours: '08:30 – 20:30',
    description: 'Оборудованная зона отдыха и проектной работы студентов со свободным доступом к розеткам.',
    tags: ['КазНУ', 'Розетки', 'Бесплатно'],
  },
  {
    id: 'outlet-kbtu-hall',
    title: 'Круглый зал КБТУ (учебная зона)',
    category: 'outlet',
    categoryLabel: 'Розетки / Учеба',
    lat: 43.2558,
    lng: 76.9435,
    address: 'ул. Толе би, 59 (КБТУ, Старая площадь)',
    isFree: true,
    priceInfo: 'По студенческому ID',
    outletCount: '25 розеток вдоль колонн',
    hours: '08:00 – 21:00',
    description: 'Исторический зал с удобными столами и электророзетками для подготовки к экзаменам.',
    tags: ['КБТУ', 'Розетки', 'Студенты'],
  },

  // --- СКИДКИ STUDCITY (DEALS & PARTNERS) ---
  {
    id: 'deal-urbo-coffee',
    title: 'URBO Coffee • Скидка -40%',
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2382,
    lng: 76.9248,
    address: 'ул. Байтурсынова, 100 (уг. Сатпаева)',
    isFree: false,
    priceInfo: 'Капучино + круассан за 650 ₸ (было 1100 ₸)',
    dealDiscount: 40,
    offerId: 'urbo-coffee',
    hours: '08:00 – 23:00 (Скидка до 17:00)',
    description: 'Свежеобжаренный спешелти кофе и выпечка. Есть розетки и быстрый Wi-Fi.',
    tags: ['Кофе', 'Скидка -40%', 'StudCity Партнер'],
  },
  {
    id: 'deal-zhekas-doner',
    title: "Zheka's Doner • Скидка -30%",
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2268,
    lng: 76.9205,
    address: 'ул. Тимирязева, 42 (напротив КазНУ)',
    isFree: false,
    priceInfo: 'Комбо с донером за 1400 ₸ (было 2000 ₸)',
    dealDiscount: 30,
    offerId: 'zhekas-doner',
    hours: '10:00 – 02:00 (Скидка до 16:30)',
    description: 'Сытный горячий обед между парами. Скидка доступна по динамическому QR-коду StudCity.',
    tags: ['Обед', 'Донер', 'Скидка -30%'],
  },
  {
    id: 'deal-degirmen-bakery',
    title: 'Degirmen Bakery • Скидка -45%',
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2380,
    lng: 76.9520,
    address: 'ул. Сатпаева, 16 (уг. пр. Достык)',
    isFree: false,
    priceInfo: 'Чайник чая + симит за 770 ₸ (было 1400 ₸)',
    dealDiscount: 45,
    offerId: 'degirmen-cafe',
    hours: '08:00 – 22:00 (Скидка до 16:00)',
    description: 'Турецкая выпечка, сыр, безлимитный турецкий чай и уютная атмосфера для студентов.',
    tags: ['Кафе', 'Чай', 'Скидка -45%'],
  },
  {
    id: 'deal-wok-lagman',
    title: 'Wok & Lagman Hub • Скидка -30%',
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2415,
    lng: 76.9250,
    address: 'ул. Байтурсынова, 70',
    isFree: false,
    priceInfo: 'Гуйру лагман + морс за 1260 ₸ (было 1800 ₸)',
    dealDiscount: 30,
    offerId: 'wok-lagman-hub',
    hours: '10:00 – 23:00 (Скидка до 17:30)',
    description: 'Тянутый сочный лагман и свежие блюда wok прямо рядом с кампусами.',
    tags: ['Лагман', 'Обед', 'Скидка -30%'],
  },

  // --- КОПИЦЕНТРЫ / ПЕЧАТЬ (PRINT) ---
  {
    id: 'print-master-satpaev',
    title: 'PrintMaster Копицентр • Скидка -50%',
    category: 'print',
    categoryLabel: 'Копицентр / Печать',
    lat: 43.2369,
    lng: 76.9280,
    address: 'ул. Сатпаева, 22/1 (вход со двора Политеха)',
    isFree: false,
    priceInfo: 'Печать и переплет курсовых от 300 ₸',
    dealDiscount: 50,
    offerId: 'printmaster',
    hours: '08:00 – 19:00',
    description: 'Лазерная печать А4/А3, чертежи, сканирование и твердый переплет дипломов со скидкой 50%.',
    tags: ['Печать', 'Политех', 'Скидка -50%'],
  },
  {
    id: 'print-kaznu-express',
    title: 'Экспресс-печать КазНУ (Студгородок)',
    category: 'print',
    categoryLabel: 'Копицентр / Печать',
    lat: 43.2240,
    lng: 76.9240,
    address: 'Кампус КазНУ, Студгородок, торговый павильон',
    isFree: false,
    priceInfo: 'Ч/Б печать 15 ₸/стр',
    hours: '08:30 – 18:30',
    description: 'Быстрая распечатка документов с флешки или через Telegram бота.',
    tags: ['Печать', 'КазНУ', 'Студгородок'],
  },
];
