import { MapSpot, MapSpotCategory } from '@/types';

export interface PresetPhoto {
  label: string;
  url: string;
}

export const PRESET_SPOT_PHOTOS: Record<MapSpotCategory, PresetPhoto[]> = {
  toilet: [
    {
      label: 'ТРЦ санузел (чистый, просторный)',
      url: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Университетский санузел',
      url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Городской модульный туалет',
      url: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Санузел в коворкинге / кафе',
      url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80',
    },
  ],
  wifi: [
    {
      label: 'Библиотека / тихий зал',
      url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Городской сквер / парк',
      url: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Кафе с открытым Wi-Fi',
      url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Пешеходная аллея / Арбат',
      url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
    },
  ],
  outlet: [
    {
      label: 'Коворкинг с розетками',
      url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Студенческий кампус-хаб',
      url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Учебный зал университета',
      url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Столы с индивидуальными розетками',
      url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
    },
  ],
  deal: [
    {
      label: 'Кофейня со скидкой',
      url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Студенческий ланч / донер',
      url: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    },
  ],
  print: [
    {
      label: 'Копицентр и печать',
      url: 'https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?auto=format&fit=crop&w=800&q=80',
    },
  ],
};

export const INITIAL_MAP_SPOTS: MapSpot[] = [
  // --- ТУАЛЕТЫ (TOILETS) ---
  {
    id: 'toilet-kaznu-guk',
    title: 'Общественный туалет у ГУК КазНУ',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2245,
    lng: 76.9218,
    address: 'Кампус КазНУ им. аль-Фараби, возле ГУК',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно для студентов',
    hours: '08:00 – 21:00',
    description: 'Чистый студенческий санузел с горячей водой, мылом и сушилками для рук. Доступен по студенческому билету или свободно.',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    amenities: ['Горячая вода', 'Мыло', 'Сушилка для рук', 'Зеркало', 'Бумага'],
    paymentMethods: ['Бесплатно'],
    tags: ['Кампус', 'КазНУ', 'Бесплатно', 'Чистый'],
  },
  {
    id: 'toilet-satbayev-polytech',
    title: 'Туалет в главном корпусе Satbayev University',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2375,
    lng: 76.9268,
    address: 'ул. Сатпаева, 22 (Главный учебный корпус)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    hours: '07:30 – 20:00',
    description: 'Санузел на 1 и 2 этажах ГУК Политеха. Оснащен сенсорными дозаторами и кабинками для маломобильных граждан.',
    imageUrl: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80',
    amenities: ['Сенсорные дозаторы', 'Для маломобильных', 'Зеркало', 'Бумага'],
    paymentMethods: ['Бесплатно'],
    tags: ['Satbayev', 'Политех', 'Бесплатно', 'Доступно'],
  },
  {
    id: 'toilet-promenade-mall',
    title: 'Туалет в ТЦ Promenade',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2392,
    lng: 76.9235,
    address: 'пр. Абая, 44а (уг. Байтурсынова), 2 этаж',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно для посетителей',
    hours: '10:00 – 22:00',
    description: 'Просторные бесплатные уборные в зоне фудкорта. Всегда есть туалетная бумага, жидкое мыло и большие зеркала.',
    imageUrl: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=800&q=80',
    amenities: ['Мыло', 'Туалетная бумага', 'Зеркало во весь рост', 'Сушилка'],
    paymentMethods: ['Бесплатно'],
    tags: ['ТРЦ', 'Байтурсынова', 'Бесплатно'],
  },
  {
    id: 'toilet-panfilov-street',
    title: 'Модульный туалет на ул. Панфилова',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2530,
    lng: 76.9458,
    address: 'ул. Панфилова, уг. ул. Кабанбай батыра',
    isFree: false,
    price: 50,
    priceInfo: '50 ₸ (Оплата Kaspi QR / Картой)',
    hours: 'Круглосуточно 24/7',
    description: 'Современный автоматический теплый городской модуль. Вход по бесконтактной оплате или Kaspi QR.',
    imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=800&q=80',
    amenities: ['Оплата картой / Kaspi QR', 'Теплый пол', 'Бесконтактный смыв', 'Зеркало'],
    paymentMethods: ['Kaspi QR', 'Банковская карта'],
    tags: ['Городской', 'Панфилова', '24/7', 'Kaspi QR'],
  },
  {
    id: 'toilet-metro-almaly',
    title: 'Санузел на станции метро «Алмалы»',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2520,
    lng: 76.9442,
    address: 'Станция метро Алмалы (под ул. Панфилова)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно для пассажиров',
    hours: '06:20 – 00:00',
    description: 'Официальный санузел алматинского метрополитена. Обратитесь к дежурному у турникетов.',
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
    amenities: ['Мыло', 'Бумага', 'Для пассажиров'],
    paymentMethods: ['Бесплатно'],
    tags: ['Метро', 'Алмалы', 'Бесплатно'],
  },
  {
    id: 'toilet-metro-baykonur',
    title: 'Санузел на станции метро «Байконур»',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2395,
    lng: 76.9210,
    address: 'пр. Абая / ул. Байтурсынова (метро Байконур)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно для пассажиров',
    hours: '06:20 – 00:00',
    description: 'Расположен на платформе станции метро, очень удобно для студентов Политеха и МУИТ.',
    imageUrl: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=800&q=80',
    amenities: ['Мыло', 'Бумага', 'Сушилка'],
    paymentMethods: ['Бесплатно'],
    tags: ['Метро', 'Байконур', 'Бесплатно'],
  },
  {
    id: 'toilet-dostyk-plaza',
    title: 'Санузлы ТРЦ Dostyk Plaza',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2335,
    lng: 76.9568,
    address: 'мкр. Самал-2, 111 (пр. Достык / Жолдасбекова)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    hours: '10:00 – 23:00',
    description: 'Образцовые санузлы на 1, 2 и 3 этажах (возле фудкорта и кинотеатра). Регулярная уборка каждые 20 минут.',
    imageUrl: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=800&q=80',
    amenities: ['Премиум чистота', 'Сенсорные смесители', 'Сушилки Dyson', 'Зеркала с подсветкой'],
    paymentMethods: ['Бесплатно'],
    tags: ['ТРЦ', 'Dostyk Plaza', 'Бесплатно', 'Комфорт'],
  },
  {
    id: 'toilet-panfilov-park',
    title: 'Городской туалет в Парке 28 Панфиловцев',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2592,
    lng: 76.9535,
    address: 'Парк им. 28 гвардейцев-панфиловцев (южная аллея)',
    isFree: false,
    price: 50,
    priceInfo: '50 ₸ (Kaspi QR / Наличные)',
    hours: '09:00 – 21:00',
    description: 'Стационарный парк-туалет рядом с Вознесенским собором. Есть раковины и детская зона.',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    amenities: ['Раковины', 'Мыло', 'Детская зона'],
    paymentMethods: ['Kaspi QR', 'Наличные'],
    tags: ['Парк', 'Центр'],
  },
  {
    id: 'toilet-mega-center',
    title: 'Санузлы ТРЦ MEGA Alma-Ata',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2030,
    lng: 76.8925,
    address: 'ул. Розыбакиева, 247',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    hours: '10:00 – 22:00',
    description: 'Бесплатные комфортные туалеты во всех галереях ТРЦ МЕГА.',
    imageUrl: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=800&q=80',
    amenities: ['Бесплатно', 'Сушилки', 'Зеркала', 'Для детей'],
    paymentMethods: ['Бесплатно'],
    tags: ['ТРЦ', 'МЕГА', 'Бесплатно'],
  },
  {
    id: 'toilet-arbat-passage',
    title: 'Туалет в ТЦ «Пассаж» на Арбате',
    category: 'toilet',
    categoryLabel: 'Туалет',
    lat: 43.2625,
    lng: 76.9420,
    address: 'ул. Жибек Жолы, 50 (пешеходный Арбат)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    hours: '10:00 – 21:00',
    description: 'Туалет на 3 этаже торгового центра. Удобная локация при прогулке по Арбату.',
    imageUrl: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80',
    amenities: ['Мыло', 'Бумага', 'Зеркало'],
    paymentMethods: ['Бесплатно'],
    tags: ['Арбат', 'Бесплатно', 'Центр'],
  },

  // --- БЕСПЛАТНЫЙ WI-FI (FREE WI-FI) ---
  {
    id: 'wifi-kaznu-library',
    title: 'Студенческая сеть KazNU-Open-WiFi',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2252,
    lng: 76.9230,
    address: 'Библиотека Аль-Фараби, КазНУ',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно для всех',
    wifiSpeed: '120 Мбит/с',
    wifiPassword: 'Без пароля (открытая сеть)',
    hours: '08:00 – 22:00',
    description: 'Открытая высокоскоростная сеть для студентов. Отлично подходит для скачивания учебников и видео-лекций.',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Бесплатно'],
    tags: ['Wi-Fi', 'КазНУ', '120 Mbps', 'Без пароля'],
  },
  {
    id: 'wifi-satpaev-square',
    title: 'Городской Wi-Fi в сквере Сатпаева',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2380,
    lng: 76.9275,
    address: 'Сквер им. Сатпаева (напротив Политеха)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    wifiSpeed: '65 Мбит/с',
    wifiPassword: 'SMS-авторизация (OpenAlmaty)',
    hours: 'Круглосуточно',
    description: 'Общественная точка доступа Almaty-City-WiFi с устойчивым сигналом на скамейках в парке.',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Бесплатно'],
    tags: ['Wi-Fi', 'Сквер', 'Открытая сеть'],
  },
  {
    id: 'wifi-panfilov-pedestrian',
    title: 'Открытый Wi-Fi на ул. Панфилова',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2540,
    lng: 76.9455,
    address: 'Пешеходная зона Панфилова (между Толе би и Кабанбай)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    wifiSpeed: '85 Мбит/с',
    wifiPassword: 'Без пароля',
    hours: 'Круглосуточно',
    description: 'Городской проект OpenAlmaty_WiFi. Подключение в один клик через SMS-авторизацию.',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Бесплатно'],
    tags: ['Wi-Fi', 'Панфилова', 'Улица'],
  },
  {
    id: 'wifi-arbat-free',
    title: 'Almaty Free WiFi на Арбате',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2620,
    lng: 76.9430,
    address: 'ул. Жибек Жолы (Арбат)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    wifiSpeed: '70 Мбит/с',
    wifiPassword: 'Без пароля',
    hours: 'Круглосуточно',
    description: 'Покрывает всю прогулочную зону Арбата от Абылай хана до Кунаева.',
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Бесплатно'],
    tags: ['Wi-Fi', 'Арбат', 'Бесплатно'],
  },
  {
    id: 'wifi-dostyk-plaza',
    title: 'Высокоскоростной Wi-Fi в Dostyk Plaza',
    category: 'wifi',
    categoryLabel: 'Бесплатный Wi-Fi',
    lat: 43.2338,
    lng: 76.9572,
    address: 'Самал-2, 111, ТРЦ Достык Плаза',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно',
    wifiSpeed: '150 Мбит/с',
    wifiPassword: 'Без пароля (сеть DostykPlaza_Free)',
    hours: '10:00 – 23:00',
    description: 'Сеть DostykPlaza_Free без ограничений по времени. Стабильно ловит в зоне коворкинг-кафе и фудкорта.',
    imageUrl: 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Бесплатно'],
    tags: ['Wi-Fi', 'Dostyk Plaza', '150 Mbps'],
  },

  // --- РОЗЕТКИ И МЕСТА ДЛЯ УЧЕБЫ (OUTLETS / STUDY) ---
  {
    id: 'outlet-smartspace',
    title: 'SmartSpace Coworking (розетки + столы)',
    category: 'outlet',
    categoryLabel: 'Розетки / Учеба',
    lat: 43.2398,
    lng: 76.9185,
    address: 'пр. Абая, 52/2 (ст. метро Байконур)',
    isFree: false,
    price: 1950,
    priceInfo: '1950 ₸ / день со скидкой StudCity',
    outletCount: 'Розетка у каждого места (50+)',
    hours: '09:00 – 23:00',
    description: 'Идеальное тихое место для учебы с высокоскоростным интернетом и удлинителями для ноутбуков.',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    amenities: ['Розетки 220V', 'Type-C порты', 'Тихая зона', 'Чай/кофе'],
    paymentMethods: ['Kaspi QR', 'Карта'],
    tags: ['Розетки', 'Коворкинг', 'Сессия'],
  },
  {
    id: 'outlet-kaznu-hub',
    title: 'Студенческий коворкинг ГУК КазНУ',
    category: 'outlet',
    categoryLabel: 'Розетки / Учеба',
    lat: 43.2255,
    lng: 76.9225,
    address: 'Кампус КазНУ, корпус ГУК, цокольный этаж',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно для студентов',
    outletCount: '30+ розеток и Type-C зарядки',
    hours: '08:30 – 20:30',
    description: 'Оборудованная зона отдыха и проектной работы студентов со свободным доступом к розеткам.',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
    amenities: ['Розетки 220V', 'Бесплатно', 'Столы для групп'],
    paymentMethods: ['Бесплатно'],
    tags: ['КазНУ', 'Розетки', 'Бесплатно'],
  },
  {
    id: 'outlet-kbtu-hall',
    title: 'Круглый зал КБТУ (учебная зона)',
    category: 'outlet',
    categoryLabel: 'Розетки / Учеба',
    lat: 43.2558,
    lng: 76.9435,
    address: 'ул. Толе би, 59 (КБТУ, Старая площадь)',
    isFree: true,
    price: 0,
    priceInfo: 'Бесплатно (по студенческому ID)',
    outletCount: '25 розеток вдоль колонн',
    hours: '08:00 – 21:00',
    description: 'Исторический зал с удобными столами и электророзетками для подготовки к экзаменам.',
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    amenities: ['Розетки 220V', 'Учебные парты', 'Тихая атмосфера'],
    paymentMethods: ['Бесплатно'],
    tags: ['КБТУ', 'Розетки', 'Студенты'],
  },

  // --- СКИДКИ STUDCITY (DEALS & PARTNERS) ---
  {
    id: 'deal-urbo-coffee',
    title: 'URBO Coffee • Скидка -40%',
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2382,
    lng: 76.9248,
    address: 'ул. Байтурсынова, 100 (уг. Сатпаева)',
    isFree: false,
    price: 650,
    priceInfo: 'Сет за 650 ₸ (было 1100 ₸)',
    dealDiscount: 40,
    offerId: 'urbo-coffee',
    hours: '08:00 – 23:00 (Скидка до 17:00)',
    description: 'Свежеобжаренный спешелти кофе и выпечка. Есть розетки и быстрый Wi-Fi.',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Kaspi QR', 'Карта', 'QR StudCity'],
    tags: ['Кофе', 'Скидка -40%', 'StudCity Партнер'],
  },
  {
    id: 'deal-zhekas-doner',
    title: "Zheka's Doner • Скидка -30%",
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2268,
    lng: 76.9205,
    address: 'ул. Тимирязева, 42 (напротив КазНУ)',
    isFree: false,
    price: 1400,
    priceInfo: 'Комбо за 1400 ₸ (было 2000 ₸)',
    dealDiscount: 30,
    offerId: 'zhekas-doner',
    hours: '10:00 – 02:00 (Скидка до 16:30)',
    description: 'Сытный горячий обед между парами. Скидка доступна по динамическому QR-коду StudCity.',
    imageUrl: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Kaspi QR', 'Карта', 'QR StudCity'],
    tags: ['Обед', 'Донер', 'Скидка -30%'],
  },
  {
    id: 'deal-degirmen-bakery',
    title: 'Degirmen Bakery • Скидка -45%',
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2380,
    lng: 76.9520,
    address: 'ул. Сатпаева, 16 (уг. пр. Достык)',
    isFree: false,
    price: 770,
    priceInfo: 'Чайник + симит за 770 ₸ (было 1400 ₸)',
    dealDiscount: 45,
    offerId: 'degirmen-cafe',
    hours: '08:00 – 22:00 (Скидка до 16:00)',
    description: 'Турецкая выпечка, сыр, безлимитный турецкий чай и уютная атмосфера для студентов.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Kaspi QR', 'Карта', 'QR StudCity'],
    tags: ['Кафе', 'Чай', 'Скидка -45%'],
  },
  {
    id: 'deal-wok-lagman',
    title: 'Wok & Lagman Hub • Скидка -30%',
    category: 'deal',
    categoryLabel: 'Скидка StudCity',
    lat: 43.2415,
    lng: 76.9250,
    address: 'ул. Байтурсынова, 70',
    isFree: false,
    price: 1260,
    priceInfo: 'Лагман + морс за 1260 ₸ (было 1800 ₸)',
    dealDiscount: 30,
    offerId: 'wok-lagman-hub',
    hours: '10:00 – 23:00 (Скидка до 17:30)',
    description: 'Тянутый сочный лагман и свежие блюда wok прямо рядом с кампусами.',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Kaspi QR', 'Карта', 'QR StudCity'],
    tags: ['Лагман', 'Обед', 'Скидка -30%'],
  },

  // --- КОПИЦЕНТРЫ / ПЕЧАТЬ (PRINT) ---
  {
    id: 'print-master-satpaev',
    title: 'PrintMaster Копицентр • Скидка -50%',
    category: 'print',
    categoryLabel: 'Копицентр / Печать',
    lat: 43.2369,
    lng: 76.9280,
    address: 'ул. Сатпаева, 22/1 (вход со двора Политеха)',
    isFree: false,
    price: 300,
    priceInfo: 'Печать курсовых от 300 ₸',
    dealDiscount: 50,
    offerId: 'printmaster',
    hours: '08:00 – 19:00',
    description: 'Лазерная печать А4/А3, чертежи, сканирование и твердый переплет дипломов со скидкой 50%.',
    imageUrl: 'https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Kaspi QR', 'Наличные', 'Карта'],
    tags: ['Печать', 'Политех', 'Скидка -50%'],
  },
  {
    id: 'print-kaznu-express',
    title: 'Экспресс-печать КазНУ (Студгородок)',
    category: 'print',
    categoryLabel: 'Копицентр / Печать',
    lat: 43.2240,
    lng: 76.9240,
    address: 'Кампус КазНУ, Студгородок, торговый павильон',
    isFree: false,
    price: 15,
    priceInfo: 'Ч/Б печать 15 ₸/стр',
    hours: '08:30 – 18:30',
    description: 'Быстрая распечатка документов с флешки или через Telegram бота.',
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=800&q=80',
    paymentMethods: ['Kaspi QR', 'Наличные'],
    tags: ['Печать', 'КазНУ', 'Студгородок'],
  },
];
